name: GatewayAuth

on:
  push:
    paths:
      - ".github/workflows/build.yaml"
      - "build.sh"
      - "src/**"
      - "frontend/**"

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.16.3'
          
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14.15.4'

      - name: Prepare
        run: |
          go get -u github.com/go-bindata/go-bindata/...
          go-bindata -version
          npm install -g yarn

      - name: Build
        run: |
          cd frontend
          yarn install
          cd ..
          go mod vendor
          ./build.sh

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: build # The folder the action should deploy.


