name: GatewayAuth

on:
  push:
    paths:
      - ".github/workflows/build.yaml"
      - "src/**"
      - "frontend/**"

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install sudo package
        run: apt update && apt install sudo

      - name: build
        run: |
          sudo apt-get update && sudo apt-get install wget

